### PR TITLE
Websocket for invoice subscription

### PR DESCRIPTION
**Pull request by ShahanaFarooqui**
Websocket for invoice subscription

### CODE REVIEW

**Comment by PatrickGeyer** [comment]
Are websocket events only available when run as plugin?

**Comment by ShahanaFarooqui** [comment]
@PatrickGeyer no they are available in both setups.

**Comment by PatrickGeyer** [comment]
image
Are you sure? Looks like the above code only broadcasts events after subscribing in the plugin.js file.

**Comment by ShahanaFarooqui** [comment]
I am 100% sure as I have tested it without plugin setup also.

**Comment by PatrickGeyer** [comment]
image

Haha ok nice, is there somehow I have to subscribe to the events?
Am connecting to the c-rest-server like above, and receive any messages back that I send to it, so websocket functioning, just not receiving any events from actual lightning payments..

**Comment by PatrickGeyer** [comment]
How could I receive notifications for 'sendpay_success' event for example?

**Comment by PatrickGeyer** [comment]
Hows progress on this going?

**Comment by ShahanaFarooqui** [comment]
Haven’t started working on it yet. Busy with life but it is on my high priority list. I will work on it as soon as I am back on the track. Hopefully in 3-4 days, I will have better update. Thank you for your patience.

**Pull request merged**
