### PR TITLE
added a sort_by criteria to listForwardsPaginated

### PR DESCRIPTION
**Pull request by lightningorb**
The forwarding events returned by listForwardsPaginated are unsorted. Added ability to sort them by `received_time` or `resolved_time` with the `sort_by` attribute.

### CODE REVIEW

**Review by ShahanaFarooqui — COMMENTED** [review]
We intentionally removed sorting from listforwards as it is already the most expensive API and we do not want to increase the response time. The RPC call returns the sorted list with DESC `received_time` order. 

If it is not something which has broken your application, I am not keen on adding this again. I understand that it is an optional feature and devs can ignore it by not sending `sort_by` feature but in practice they usually send it assuming that the RPC is not already sending sorted data. 

We want RPC calls to give us the option to sort and filter the data. Once that is available, we intend to remove other sort and filtering from CL-REST as well.

**Comment by lightningorb** [comment]
> The RPC call returns the sorted list with DESC received_time order

Ah ok.  When calling `listforwards` it appears the events are unsorted.

```python
fwd = ln.listforwards().forwards

for i in range(1, len(fwd)):
    p, e = fwd[i - 1].received_time, fwd[i].received_time
    print(((">="[p == e]), "<")[p < e], end="")
```

Output:

```
<>><<><<<><><<<>><<<><<><<><<><<<<<<<><><<<<<<><<><<<<<<<><<<><<><>><<<>
```

Looking at [wallet.c](https://github.com/ElementsProject/lightning/blob/master/wallet/wallet.c):

```c
stmt = db_prepare_v2(
     w->db,
     SQL("SELECT"
  "  f.state"
  ", in_msatoshi"
  ", out_msatoshi"
  ", hin.payment_hash as payment_hash"
  ", in_channel_scid"
  ", out_channel_scid"
  ", f.received_time"
  ", f.resolved_time"
  ", f.failcode "
  ", f.forward_style "
  "FROM forwarded_payments f "
  "LEFT JOIN channel_htlcs hin ON (f.in_htlc_id = hin.id) "
  "WHERE (1 = ? OR f.state = ?) AND "
  "(1 = ? OR f.in_channel_scid = ?) AND "
  "(1 = ? OR f.out_channel_scid = ?)"));
```

The query appears to be unsorted, but please inform if overlooked something.

Thank you.

**Comment by lightningorb** [comment]
> If it is not something which has broken your application, I am not keen on adding this again.

listforwards is of no use unsorted. So yes our application has an assert if the paginated events are unsorted, since if they are unsorted we'd need to re-fetch them in their entirety on every single call.

When they are sorted, we simply match the offset_id with the database ID to only fetch the new events. That, in conjunction with your caching is very optimal.

I think the misunderstanding stems from the assertion that forwardevents returns events sorted by received_time which appears to be incorrect.

> in practice they usually send it assuming that the RPC is not already sending sorted data

They appear to be correct in that assumption.

**Comment by lightningorb** [comment]
If you are concerned with not slowing down this call, you could cache whether listforwards is returning sorted events, or not. So the first call would add O(N) (to ascertain if sorted) but subsequent calls would have no overhead.

Given the server is barely ever restarted, the overhead is infinitesimal. Happy to make this change.

**Comment by ShahanaFarooqui** [comment]
> The query appears to be unsorted, but please inform if overlooked something.

I am assuming that the list doesn't need explicit sorting because the record with highest received_time will automatically be added on the top of the list. So a simple select query will also return DESC sorted data on received_time.


> listforwards is of no use unsorted. So yes our application has an assert if the paginated events are unsorted, since if they are unsorted we'd need to re-fetch them in their entirety on every single call.

As already discussed, I am happy to merge the update if it broke your logic. AFAIK, this endpoint was added very recently and already had sorting logic. Adding it back will not break anything, will increase the response time only.


> If you are concerned with not slowing down this call, you could cache whether listforwards is returning sorted events, or not. So the first call would add O(N) (to ascertain if sorted) but subsequent calls would have no overhead.

We are already caching `failed` and `local_failed` forwards for 10 minutes. However, we do not want to serve cached data for list forwards which is more critical for users and should be freshly fetched. 

Let me know if the PR is ready as per your need and I will merge it.

**Comment by lightningorb** [comment]
> I am assuming that the list doesn't need explicit sorting because the record with highest received_time will automatically be added on the top of the list.

I'm not enough of an SQL person to be super confident about my explanation, however it may appear that in SQL land ordering is non-deterministic without an explicit orderby. https://stackoverflow.com/a/21371444 and different implementations may yield different results without orderby (Postgres 12 in my case).

In my case, the results are completely unsorted:

```python
fwd = ln.listforwards().forwards

for f in fwd:
    print(arrow.get(f.received_time))
```

Output:

```
...

2022-08-25T17:06:47.774000+00:00
2022-08-26T15:35:28.482000+00:00
2022-08-26T15:35:58.051000+00:00
2022-09-02T05:55:48.964000+00:00
2022-08-28T18:51:41.150000+00:00
2022-09-02T16:42:55.379000+00:00
2022-08-25T17:07:10.876000+00:00
2022-08-31T13:25:21.220000+00:00
2022-09-02T16:43:17.533000+00:00
2022-08-26T15:36:34.660000+00:00
2022-08-25T17:07:18.964000+00:00
2022-08-27T09:41:04.551000+00:00
2022-08-28T18:51:48.954000+00:00
2022-09-01T20:20:49.194000+00:00
2022-08-25T17:07:33.794000+00:00
...
```

As such, we (and our users on postgres) definitely need ordered paginated events, else we have to re-download the entire history on each query which is not workable.

**Comment by ShahanaFarooqui** [comment]
Thank for the explanation, it makes more sense now. Thank you for the PR, it has been merged in Release 0.9.1 branch.

**Pull request merged**
